## 12_report_generation.R -----------------------------------------------------
## Builds report/analysis_report.md from the saved result objects. Every number
## is read from a derived file; none is typed by hand.

source("R/00_setup.R")
log_msg("=== 12 report ===")

pr  <- readRDS(file.path(PATH$derived, "06_primary.rds"))
sec <- readRDS(file.path(PATH$derived, "07_secondary.rds"))
sn  <- readRDS(file.path(PATH$derived, "08_sens.rds"))
fnd <- readRDS(file.path(PATH$derived, "02_findings.rds"))
alt <- if (file.exists(file.path(PATH$derived, "09_alt.rds")))
  readRDS(file.path(PATH$derived, "09_alt.rds")) else NULL
mis <- if (file.exists(file.path(PATH$derived, "14_missing.rds")))
  readRDS(file.path(PATH$derived, "14_missing.rds")) else NULL
rad_yield <- if (file.exists(file.path(PATH$tables, "T10_radiology_text_yield.csv")))
  utils::read.csv(file.path(PATH$tables, "T10_radiology_text_yield.csv")) else NULL
meds <- if (file.exists(file.path(PATH$derived, "15_meds.rds")))
  readRDS(file.path(PATH$derived, "15_meds.rds")) else NULL
med_tip <- if (file.exists(file.path(PATH$tables, "T13b_anchored_tipping_point.csv")))
  utils::read.csv(file.path(PATH$tables, "T13b_anchored_tipping_point.csv")) else NULL
med_tip2 <- if (file.exists(file.path(PATH$tables, "T13d_anchored_tipping_extrapolated.csv")))
  utils::read.csv(file.path(PATH$tables, "T13d_anchored_tipping_extrapolated.csv")) else NULL
rad_gain <- if (file.exists(file.path(PATH$tables, "T10b_radiology_text_vs_structured.csv")))
  utils::read.csv(file.path(PATH$tables, "T10b_radiology_text_vs_structured.csv")) else NULL
a   <- readRDS(file.path(PATH$derived, "05_analytic.rds"))

get_sens <- function(pattern) {
  r <- sn$sens[grepl(pattern, sn$sens$analysis, fixed = TRUE), ][1, ]
  sprintf("%s (%s events)", r$estimate, r$events)
}
md <- function(...) paste0(..., collapse = "")

tbl_md <- function(df, digits = 3) {
  df <- as.data.frame(df)
  num <- vapply(df, is.numeric, logical(1))
  df[num] <- lapply(df[num], function(x) format(round(x, digits), trim = TRUE))
  hdr <- paste("|", paste(names(df), collapse = " | "), "|")
  sep <- paste("|", paste(rep("---", ncol(df)), collapse = " | "), "|")
  rows <- apply(df, 1, function(r) paste("|", paste(r, collapse = " | "), "|"))
  paste(c(hdr, sep, rows), collapse = "\n")
}

corrected <- sn$sens[grepl("CORRECTED PRIMARY", sn$sens$analysis), ][1, ]
asis      <- sn$sens[grepl("no landmark", sn$sens$analysis), ][1, ]

txt <- c(
"---",
"title: \"IIH and Incident Epilepsy: Analysis Report\"",
"---",
"",
"# Incident Seizures and Epilepsy After Idiopathic Intracranial Hypertension",
"",
"### Analysis report",
"",
sprintf("**Protocol:** v2.0 · **Analysis date:** %s · **Seed:** %d · **R:** %s",
        format(Sys.Date()), SEED, R.version.string),
"",
"---",
"",
"## 1. Headline result",
"",
sprintf("Among %s patients coded as IIH and %s matched non-IIH controls, the cause-specific hazard of a first incident coded seizure or epilepsy over three years was:",
        format(sum(a$iih == 1), big.mark = ","), format(sum(a$iih == 0), big.mark = ",")),
"",
sprintf("> **HR %s** (corrected primary specification, %d events)", corrected$estimate, corrected$events),
"",
sprintf("Three-year absolute risk was %.2f%% in IIH versus %.2f%% in controls, a difference of %.2f percentage points (%.2f to %.2f), or one additional seizure per %d patients followed three years.",
        pr$rd$iih_risk_pct, pr$rd$control_risk_pct, pr$rd$estimate, pr$rd$lo, pr$rd$hi,
        pr$rd$number_needed_to_harm),
"",
"**This is an association, not a demonstration that IIH causes epilepsy.** Section 6 sets out why.",
"",
"---",
"",
"## 2. Estimand",
"",
"| Element | Specification |",
"| --- | --- |",
"| Population | Matchable patients coded as IIH (ICD-9 348.2 / ICD-10 G93.2) aged 13-60, and their matched non-IIH controls |",
"| Exposure | An IIH diagnosis code, **not chart-adjudicated IIH** (protocol v2.0 change #1) |",
"| Outcome | First incident seizure/epilepsy by the coded algorithm (protocol s4.1), applied identically in both arms |",
"| Time zero | Date of diagnostic lumbar puncture; controls inherit their case's index date |",
"| Contrast | Cause-specific hazard ratio, 0.5-3 years after index |",
"| Competing event | Death, handled as a competing risk (Aalen-Johansen for absolute risk) |",
"| Censoring | Earliest of first seizure, death, last documented encounter, study end |",
"",
"The **cause-specific** hazard is primary because the question is aetiological. The Fine-Gray subdistribution hazard is reported alongside it because it answers a different, prognostic question; the two agree closely here (see section 4).",
"",
"---",
"",
"## 3. A design defect found in the data, and how it was handled",
"",
"Protocol v2.0 s2.1 treats a seizure within 180 days of index as a *presenting* rather than incident event and excludes it. **That rule was applied to cases only.** In this export:",
"",
"- the earliest incident event in an IIH case is on day 183;",
"- the earliest in a control is on day 16;",
"- **14 control events** fall inside a window in which no case can have an event by construction.",
"",
"Comparing the arms from day 0 therefore compares a case arm with a 180-day blanking period against a control arm without one. This biases the hazard ratio **toward the null**.",
"",
sprintf("| Specification | Events | HR (95%% CI) |"),
"| --- | --- | --- |",
sprintf("| Protocol as written (from day 0) | %d | %s |", asis$events, asis$estimate),
sprintf("| **Symmetric 180-day window (corrected)** | %d | **%s** |", corrected$events, corrected$estimate),
"",
"The corrected specification applies the same outcome-eligibility window to both arms via delayed entry. It is the estimate reported above, and it is what the protocol's own eligibility rule actually defines. **This requires the investigators' confirmation** (section 8).",
"",
"---",
"",
"## 4. Primary results",
"",
"### Incidence rates",
"",
tbl_md(pr$rates[, c("horizon", "cohort", "n", "events", "person_years",
                    "rate_per_1000py", "lo", "hi")], 2),
"",
"All person-time is administratively censored at the 31 August 2026 data freeze. This removes 0.2% of case and 0.8% of control person-time and leaves the 3-year primary estimate unchanged; projected end-of-follow-up ran to 2031 in cases and 2034 in controls before the cap.",
"",
"The control rate *falls* as the horizon lengthens while the case rate is stable: control person-time accrues without events. Full follow-up is the least reliable column, because case person-time is computed from an encounter-date field containing impossible values (to 2038).",
"",
"### Models",
"",
tbl_md(pr$models[, c("model", "n", "events", "estimate")]),
"",
"### Competing risk",
"",
tbl_md(pr$cr[, c("estimand", "estimate", "interpretation")]),
"",
"The cause-specific and subdistribution estimates are nearly identical because death is uncommon over three years. The **death hazard itself is markedly below 1**, which is either a genuine feature of the cohorts or an artefact of differential death ascertainment; the two cannot be separated here and it is a priority question for the data team.",
"",
"### Proportional hazards",
"",
tbl_md(pr$ph),
"",
"PH holds at 3 years and fails over full follow-up, exactly as protocol v2.0 change #4 anticipated. This is the reason for truncation.",
"",
"---",
"",
"## 5. Is the result just healthcare contact?",
"",
"This is the central threat: IIH patients see doctors far more often (post-index encounter median 81 vs 17), so they have more opportunity to be *detected* as having a seizure.",
"",
"Three lines of evidence bear on it.",
"",
"**1. The negative-control outcome is null.**",
"",
tbl_md(sec$neg[, c("outcome", "n", "ev", "estimate", "p")]),
"",
"Carpal tunnel syndrome has no plausible causal link to IIH and is ascertained the same way over the same window. If the design were simply measuring healthcare contact, it would be elevated too. It is not. This is the strongest single argument that the seizure result is not pure ascertainment.",
"",
"**2. The excess risk is sustained, not concentrated at diagnosis.**",
"",
tbl_md(sec$tsplit[, c("period", "events", "estimate")]),
"",
"A detection artefact from the diagnostic work-up would produce a spike early and decay. The opposite is seen. (The 0-6 month row is uninterpretable for the reason given in section 3.)",
"",
"**3. Adjusting for contact attenuates but does not eliminate the association.**",
"",
sprintf("Adjusted for post-index encounters: %s. This is reported as a **conservative lower bound only** (protocol s5.3). Post-index encounters are a consequence of both the exposure and the outcome, so conditioning on them is adjustment for a mediator and opens a collider path; it can push an estimate past the null even when a true effect exists. The legitimate design-stage control is the pre-index encounter restriction, and adjusting for *pre-index* contact gives %s.",
        get_sens("Adjusted for post-index encounters"),
        get_sens("Adjusted for pre-index encounters")),
"",
"---",
"",
"## 6. What would overturn this result",
"",
"### The tipping point is uncomfortably close",
"",
tbl_md(sn$tip),
"",
"If roughly **1% of censored controls had an unrecorded seizure**, the association would disappear. This follows directly from the very low control event count (83 events among 9,742 controls): a small absolute number of hidden events is a large proportional change. This is the study's most serious quantitative vulnerability.",
"",
"What argues against it: the null negative control, and the fact that controls were required to have an encounter in the year before index, so they are not disengaged patients. What cannot be ruled out: controls have **no date fields at all** in this export, so their censoring cannot be independently verified.",
"",
"### E-value",
"",
tbl_md(pr$evalue),
"",
"### Outcome misclassification",
"",
tbl_md(sn$mis),
"",
"Non-differential misclassification does not move the rate ratio at all (it scales both arms equally). Only *differential* detection does. Sensitivity would have to be substantially better in cases than controls to account for the finding.",
"",
"---",
"",
"## 7. Sensitivity analyses",
"",
tbl_md(sn$sens[, c("analysis", "status", "n", "events", "estimate", "p")]),
"",
"---",
"",
"## 7b. Effect modification",
"",
tbl_md(alt$sub[, c("modifier", "subgroup", "n", "events", "estimate", "interaction_p")]),
"",
"Subgroup hazard ratios are descriptive. Whether the effect differs is judged **only** by the interaction p-value, never by which subgroup reached significance. With 112 events these tests have low power, so a large p-value does not establish a uniform effect.",
"",
"The one signal worth following up is **BMI (interaction p = 0.023)**: the association is stronger in patients with BMI <35 (5.54) than >=35 (2.29). Two readings compete, and this analysis cannot separate them. Either IIH coded in a non-obese patient is more often a secondary or miscoded intracranial hypertension with its own seizure risk, or obesity-related confounding dilutes the estimate in the high-BMI stratum. This is post hoc.",
"",
"### Restricted mean time lost to seizure",
"",
tbl_md(alt$rmtl[, c("quantity", "estimate")]),
"",
"Days spent in the post-seizure state per patient over three years. This requires no proportional-hazards assumption and treats death as a competing event, so it is a useful companion to the hazard ratio rather than a restatement of it.",
"",
"---",
"",
"## 7c. Missing data",
"",
tbl_md(mis$comp[, c("approach", "n", "ev", "estimate", "note")]),
"",
"Complete-case, missing-indicator and multiple imputation agree to two decimal places. This is not a coincidence: only 12 of 12,204 rows are missing any adjustment-set variable. **Missing data is not a material threat to this analysis.**",
"",
"What *is* material is structural absence, which imputation must never touch:",
"",
tbl_md(mis$wide),
"",
"---",
"",
"## 7d. Radiology free text (exploratory, not validated)",
"",
"3,115 MRI reports link to 2,808 of 3,601 IIH cases and to **zero controls**, so nothing here can support a case-control comparison.",
"",
tbl_md(rad_yield),
"",
"A negation-aware extractor classified each report as positive, negated, or **not mentioned** - the last being a distinct category, never a negative.",
"",
tbl_md(rad_gain),
"",
"**The yield is modest.** Only 4.1% of reports discuss the skull base at all, so encephalocele assessability rises from 90 cases to about 135, not to thousands. Where both sources speak, agreement is high (65 of 69 for encephalocele). This does not revive the mediation aim.",
"",
"No output of this extraction enters any model. `S23_radiology_review_sample.csv` contains 214 reports (all 97 text-positive plus stratified samples of the rest, with sampling fractions recorded) for blinded review before any of it is used.",
"",
"---",
"",
"## 7e. Medications: an empirical anchor for the tipping point (provisional)",
"",
"The medication extract covers **2,821 of 9,742 matched controls (29%) and zero IIH cases**. It therefore still cannot support the acetazolamide-only restriction, time-varying treatment models or a marginal structural model - and acetazolamide does not appear anywhere in the extract.",
"",
"Three checks pass cleanly:",
"",
"- **Classification matches protocol section 4.2.** Gabapentin (2,971 rows) and pregabalin (742) are classified as gabapentinoids and not counted as ASMs; topiramate (458) is classified as IIH treatment; benzodiazepines are excluded. Zonisamide is counted.",
"- **No cohort contamination.** 59 IIH cases surfaced in the control extract; none was used as a matched control.",
"- **The pre-index ASM exclusion held.** Every discordant control below started their ASM after index.",
"",
"### The finding that matters",
"",
sprintf("**%d of %d controls with medication data (%.2f%%) received an unambiguous antiseizure medication but were never coded with epilepsy.** Levetiracetam (32) and lamotrigine (14) dominate.",
        meds$n_disc, meds$n_with_med, 100 * meds$n_disc / meds$n_with_med),
"",
"Until now the tipping-point analysis was hypothetical. These are named patients, and their first ASM date gives a real event time rather than an invented one.",
"",
"**Scenario 1 - observed candidates only:**",
"",
tbl_md(med_tip),
"",
"Even assuming every one is a true missed seizure, the association survives (1.98, 1.42-2.75).",
"",
"**Scenario 2 - extrapolating the same rate to the 71% of controls with no medication data:**",
"",
tbl_md(med_tip2),
"",
"Here the null **is** reached at about half. So the reassurance from scenario 1 is conditional on the medication-covered controls being representative, which is untested.",
"",
"### The asymmetry that decides it",
"",
"Both scenarios add hidden events to controls and none to cases, because **no case medications were extracted**. That is the worst case by construction and is almost certainly wrong - IIH patients also receive levetiracetam and lamotrigine for non-epilepsy reasons. If the ASM-without-diagnosis rate is similar in both arms the misclassification is non-differential and the hazard ratio moves very little.",
"",
"The whole question turns on whether that rate differs by exposure, and this extract cannot answer it. **Extracting the same medication data for the 2,732 matched IIH cases is now the highest-value single addition to the study.**",
"",
"---",
"",
"## 8. Analyses that could NOT be done, and why",
"",
"These were requested but are not supported by this export. None was approximated.",
"",
"| Planned analysis | Why not |",
"| --- | --- |",
"| Cumulative IIH burden gradient (mild/moderate/severe) | No severity variable exists. Shunt/stent is a post-index decision and is not a baseline severity marker. |",
"| Restricted cubic spline for opening pressure | Recorded in 70% of cases; 42 events among those with a value. Knot placement would be set by a handful of events. A linear term is reported instead, and is null. |",
"| Time-varying treatment / marginal structural model | No medication start or stop dates exist. |",
"| Acetazolamide-only restriction | No per-drug data. |",
"| Encephalocele mediation (natural, interventional or separable effects) | Mediator measured in 2.5% of cases and 0% of controls; 8 events in the assessable subgroup. Not identifiable, not merely underpowered. Protocol v2.0 change #8 already suspends it. |",
"| Algorithm PPV, sensitivity, confusion matrix | No blinded review sample (v2.0 change #7). |",
"| Cohen's kappa (adjudication), imaging reader kappa | No double-read or overlap sample. |",
"| Stricter outcome (criterion 1 only) | `outcome_criterion` is populated for controls only. Applying it would drop control events while keeping every case event and would inflate the HR by construction. |",
"| GERD negative control | Never extracted. |",
"| Drug-resistant epilepsy, Engel class, lesionectomy outcomes | Not extracted. |",
"| Reverse cohort (epilepsy then IIH) | Requires an epilepsy-indexed cohort that does not exist here. |",
"",
"---",
"",
"## 9. Data quality findings",
"",
tbl_md(fnd[fnd$severity %in% c("CRITICAL", "MAJOR"), c("id", "severity", "finding")]),
"",
"Full list, including detail and consequence, in `outputs/tables/S9_audit_findings.csv`.",
"",
"---",
"",
"## 10. Why this is not evidence that IIH causes epilepsy",
"",
"1. **The exposure is a code, not a diagnosis.** Friedman adjudication was dropped. Among cases with a recorded opening pressure, 29% are below the 25 cmH2O diagnostic threshold. The cohort is 'patients coded as IIH'.",
"2. **Confounding by indication for investigation.** Both IIH and seizure prompt neuroimaging and neurology referral. Matching on age, sex and BMI does not close that path; the null negative control constrains it but does not eliminate it.",
"3. **The control event rate is low enough that small differential under-ascertainment reverses the finding** (section 6).",
"4. **Follow-up is not comparable** and case person-time is demonstrably contaminated by impossible dates.",
"5. **No mechanism is demonstrated.** The structural hypothesis (skull-base thinning and temporal encephalocele) is untestable in this data.",
"6. **Residual confounding** by sleep apnoea, PCOS and hypertension is present and unadjusted: these are imbalanced after matching (SMD 0.36, 0.16, 0.17) and were not matching targets.",
"",
"The defensible claim is: *patients carrying an IIH diagnosis code have a substantially higher recorded rate of incident seizure and epilepsy than matched non-IIH patients, and this is not explained by the amount of healthcare contact alone.*",
"",
"---",
"",
"## 11. Reproducibility appendix",
"",
sprintf("- **Seed:** %d (set in `R/00_setup.R`)", SEED),
sprintf("- **R version:** %s", R.version.string),
sprintf("- **Analysis date:** %s", format(Sys.time(), "%Y-%m-%d %H:%M")),
"- **Key packages:**",
paste0("  - ", paste(sapply(c("survival", "ggplot2"), function(p)
  sprintf("%s %s", p, as.character(utils::packageVersion(p)))), collapse = "\n  - ")),
"- **Raw data:** `data-raw/IIH_MASTER_cases_and_controls_2.csv`, opened read-only and never modified.",
"- **Pipeline:** `Rscript run_all.R` reruns everything from a clean session.",
"",
"### Model formulas",
"",
"```",
"Primary (corrected):  coxph(Surv(t0, t, ev) ~ iih, cluster = match_set, robust = TRUE)",
"                      t0 = 180/365.25, t = min(followup_years, 3)",
"Stratified:           coxph(Surv(t0, t, ev) ~ iih + strata(match_set))",
"IPTW:                 coxph(Surv(t0, t, ev) ~ iih, weights = stabilised trimmed IPTW,",
"                            cluster = match_set, robust = TRUE)",
"Fine-Gray:            coxph(Surv(fgstart, fgstop, fgstatus) ~ iih, weights = fgwt)",
"Propensity score:     glm(iih ~ age_index + bmi_index + sex + index_year, binomial)",
"```",
"",
"### Exclusions applied inside this pipeline",
"",
"- Rows with missing or non-positive follow-up.",
"- Unmatched IIH cases (n = 869) from all comparative analyses; retained for description.",
"- For the stratified model only: matched sets containing a single arm.",
"",
"No other observations were dropped. Sentinel codes 88 and 99 were never converted to zeros.",
"")

writeLines(txt, file.path(PATH$report, "analysis_report.md"))
log_msg("wrote report/analysis_report.md")

if (requireNamespace("rmarkdown", quietly = TRUE)) {
  ok <- tryCatch({
    rmarkdown::render(file.path(PATH$report, "analysis_report.md"),
                      output_format = rmarkdown::html_document(
                        toc = TRUE, toc_float = TRUE, theme = "flatly",
                        df_print = "kable"),
                      quiet = TRUE); TRUE
  }, error = function(e) { log_msg("HTML render skipped: ", conditionMessage(e)); FALSE })
  if (ok) log_msg("wrote report/analysis_report.html")
}
log_msg("12 complete")
